# Generated by Django 5.1.5 on 2025-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mebellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('narxi', models.IntegerField(default=0)),
                ('izoh', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mebellar',
                'db_table': 'mebellar',
            },
        ),
    ]
