# Generated by Django 5.1.5 on 2025-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebellar',
            name='rasmi',
            field=models.ImageField(upload_to='images/', verbose_name='RASMI:'),
        ),
    ]
