# Generated by Django 5.1.5 on 2025-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_alter_mebellar_rasmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='images/', verbose_name='RASMI:')),
                ('izoh', models.TextField(max_length=100)),
                ('yonalish', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bolim',
                'db_table': 'bolimlar',
            },
        ),
    ]
