# Generated by Django 5.1.5 on 2025-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_bolim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='images/', verbose_name='RASMI:')),
            ],
            options={
                'verbose_name_plural': 'Postlar',
                'db_table': 'postlar',
            },
        ),
    ]
