# Generated by Django 5.1.5 on 2025-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_postlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlar',
            name='nomi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
