# Generated by Django 5.1.5 on 2025-02-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_izohlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izohlar',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
